# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Workout App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workout App
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'


  target 'Workout AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Workout AppUITests' do
    # Pods for testing
  end

end
